pngwn/MDsveX

README.md, src/md/codeParse.ts, src/parse.ts, test/parse.spec.ts
Adds support for writing module scripts in markdown using the following syntax:
````jsx
```js module
export function someFunction(value) {
// some stuff here
}
```
````
Includes documentation.
=> Module scripts

README.md
So glad this package exists. Thanks :+1: 
Without this flag a prerendered sapper page will display 404 for these routes.
=> docs: Extend --ext notice to export

README.md
Adds a missing `import * as path from "path";` statement needed to get this running. Can be confusing for beginners if they don't know what is going on.
=> adds missing instruction

src/parse.ts
Currently styles are not being reset like modules, meaning that styles are being copied to other pages. This adds the reset.
=> Reset styles

src/transformers/index.js, test/it/code_highlighting.test.js
I found an issue with the improvement i made yesterday.
```js
const s = ["one","two"].join("\n")
```
looks like this in the output rendered by a browser:
```
const s = ["one","two"].join("
")
```
Not sure if it's the svelte compiler or the innerHtml at runtime, but additional escaping seems to help.
So here it is. Sorry this slipped through.
=> [fix] escape CR LF TAB literals so that they are rendered correctly in final highlight output

site/src/routes/_docs.svtext
This is a really quick fix that *almost* closes #50, because 
> I'll also add a warning when layouts is used as an option instead of layout. TS types will help here also.
remains unresolved.
=> docs: replace references to nonexistent config option `layouts` with `layout`

site/src/routes/_docs.svtext
remark & rehype renamed `master` to `main`, so the links to their respective plugin lists were broken.
=> fix broken links to remark & rehype plugins lists

packages/mdsvex/src/index.ts, packages/mdsvex/src/types.ts, packages/mdsvex/test/it/mdsvex.test.ts, packages/site/src/components/_cheatsheet.svtext, packages/site/src/routes/_docs.svtext, packages/site/src/routes/docs.svelte
Adds a new option: `extensions`, which acts just like `extension` but allows for an array instead. Useful for cases when files with different extensions should be processed by MDsveX (for example: including a `.md` file in a `.svx` file, while wanting GitHub to preview the `.md` one). For now, it defaults to an array with `extension` until it is deprecated and `extensions` can get a proper default (ex: `[".svx"]`)
Closes #128
=> Extensions option

packages/site/src/components/Repl/Output/index.svelte, packages/site/src/components/Repl/Repl.svelte
fix: Output has unused export property 'embedded'.  warning log
All logs
```bash
MDsveX/packages/site/src/components/Repl/Output/index.svelte
Output has unused export property 'embedded'. If it is for external reference only, please consider using `export const embedded`
16:   export let sourceErrorLoc = null;
17:   export let runtimeError = null;
18:   export let embedded = false;
^
19:   export let relaxed = false;
20:   export let injectedJS;
```
=> Remove: unused export propety embedded

packages/site/src/components/Repl/Output/Viewer.svelte, packages/site/src/components/Repl/Output/index.svelte
All cleard ` unused export property...` warning log.
logs
```
MDsveX/packages/site/src/components/Repl/Output/index.svelte
Output has unused export property 'sourceErrorLoc'. If it is for external reference only, please consider using `export const sourceErrorLoc`
export let workersUrl;
export let status;
export let sourceErrorLoc = null;
^
export let runtimeError = null;
export let relaxed = false;
MDsveX/packages/site/src/components/Repl/Output/Viewer.svelte
Viewer has unused export property 'funky'. If it is for external reference only, please consider using `export const funky`
export let injectedJS = "";
export let injectedCSS = "";
export let funky = false;
^
let iframe;
```
=> Remove: unused variables

packages/site/src/routes/_docs.svtext
The code examples makes it look like `compile` is synchronous, so I suggest adding the `await` keyword to it to match the `preprocess` example. Also spotted a little error with missing quotes in a require statement.
=> Docs - fixes to code examples

packages/svelte-parse/README.md
=> docs(svelte-parse): document correct return type of parse

packages/site/src/routes/_source.js
One character fix on the playground.
Looks like `metadata` was renamed for https://github.com/pngwn/MDsveX/issues/25, this fixes the playground referencing the old name.
=> Fixes playground docs for `metadata`

.changeset/violet-meals-reply.md, packages/mdsvex/src/index.ts, packages/mdsvex/test/it/mdsvex.test.ts
Ran into this when trying to wrangle mdsvex for a small prototype I'm working on. Basically this chunk doesn't work as-is (I think the intention was that it should):
```js
require("svelte/package.json"); // svelte is a peer dependency. 
var mdsvex = require("mdsvex")
mdsvex.compile("# Hello, world\nHi")
```
https://runkit.com/embed/h4ze1371hmyq
=> Handle no options gracefully in compile

.changeset/moody-carpets-switch.md, .changeset/violet-meals-reply.md, packages/mdsvex/src/index.ts, packages/mdsvex/test/it/mdsvex.test.ts
This builds on changes in #185, which should be merged first.
=> Silence spurious compile warnings

.changeset/honest-geese-drum.md, packages/svelte-parse/src/main.ts
This fixes the production build on my pc.
=> Add checks for null/undefined to keep ts happy

.changeset/orange-scissors-push.md, packages/mdsvex/package.json, packages/mdsvex/src/index.ts, packages/mdsvex/test/it/mdsvex.test.ts, pnpm-lock.yaml
This PR changes the current plugin order for remark plugins, running builtin in code highlighting after all user-provided plugins have run.
Fixes: #93
=> Change plugin order

.changeset/tiny-pants-love.md, packages/mdsvex/src/index.ts, packages/mdsvex/src/types.ts, packages/mdsvex/test/it/mdsvex.test.ts
Standalone `compile()` function now returns headmatter data too.
Export all types in case others want to use them.
Added tests, and all tests passing.
I added the `changeset` thing, not sure what I'm doing there. :)
=> Standalone `compile()` function now returns headmatter data too.

packages/site/src/routes/_docs.svtext
=> Clarify need to import prism theme css to get syntax highlighting

.changeset/forty-bananas-fly.md, packages/mdsvex/src/transformers/index.ts
Do this by allowing the highlighting function to go through in browser
build -- it won't highlight, but it will escape.
=> Escape code chunks in browser builds

.changeset/modern-beds-drive.md, packages/mdsvex/src/transformers/index.ts, packages/mdsvex/src/types.ts, packages/mdsvex/test/it/code_highlighting.test.ts
Pass metastring to custom highlight functions. Closes #146.
=> feat(mdsvex): pass metastring to custom highlight functions

.github/workflows/mdsvex.yaml
I noticed that the CI was running Node 12 and 14. Not sure if you want to drop 12 or not, but I thought it'd make sense to add 16 at least
=> Add Node 16 to CI. Drop Node 12

packages/mdsvex/src/index.ts
want to start out by saying that this is a fantastic project and I really enjoy using it.
I don't know what the proper way of adding this information to the error message would be since I don't typically add information to errors and then rethrow them but this sovles a problem that I've ran into several times now
before
```
Identifier is expected
ParseError: Identifier is expected
```
after:
```
Identifier is expected (113:3)
111:     position: relative;
112:     
113:     &:after {
^
114:       content: '';
115:       position: absolute;
at /xxx/src/lib/layouts/default.svelte
```
=> add information to error

packages/site/src/routes/_docs.svtext
make users aware of the need to specify extensions in two places 
closes #380
=> [docs] make users aware of the need to specify extensions in two places

packages/site/src/components/Repl/CodeMirror.svelte
This was done upstream in https://github.com/sveltejs/svelte-repl/commit/729cd86b131329d0118676cabc0e45a054798b10 and would be needed if we want to run the site on SvelteKit (https://github.com/pngwn/MDsveX/issues/317)
=> Copy CodeMirror changes from upstream for SvelteKit support

.changeset/modern-bears-pull.md, packages/mdsvex/package.json, packages/mdsvex/src/define-config.ts, packages/mdsvex/src/main.ts
Closes #300
For now I'm exporting the types starting from `MDSvex`, but I wonder if more types can be made public, like the SmartyPants one
=> defineMDSveXConfig

packages/site/src/routes/_docs.svtext
The current docs are a bit unclear of how to use custom components with HTML tags such as `<img>`. For example, this does **NOT** work because the `<img>` tag is not rendered in the slot:
```
<div id="image-container">
<slot/>
</div>
```
Instead, the user may do:
```
<script>
export let src;
</script>
<div id="image-container">
</div>
```
This change clarifies this behavior in the docs.
=> Clarify how to recieve props of regular HTML tags

packages/mdsvex/src/types.ts, packages/site/src/routes/_docs.svtext
[docs] note that highlight function can be async
justification
https://github.com/pngwn/MDsveX/blob/6c60fe68c335fce559db9690fbf5e69ef539d37d/packages/mdsvex/src/types.ts#L157
=> [docs] note that highlight function can be async

packages/mdsvex/package.json
Adds Svelte 5. Currently, this may only be installed alongside Svelte 5 with `--legacy-peer-deps` or `--force`
See https://github.com/pngwn/MDsveX/issues/555 
Users on that issue report being able to use the library with Svelte 5, except for the peer dependency issue. I also recently implemented a blog with `"mdsvex": "^0.11.0"` and `"svelte": "^5.0.0-next.1"`.
It looks like testing happens with Svelte 4. If desired I could try to matrix the version.
=> allow svelte 5 in peerDependencies

packages/mdsvex/src/transformers/index.ts, packages/mdsvex/test/_fixtures/hybrid/input/dollar-one-in-frontmatter.svx, packages/mdsvex/test/_fixtures/hybrid/output/dollar-one-in-frontmatter.svelte
Without this change, the script itself could be inserted into the metadata string.
Before,
```
---
price: '$10'
---
<script context="module">
</script>
```
becomes
```svelte
<script·context="module">
export const metadata = {"price":"<script·context="module">0"};
const {·price·} = metadata;
</script>
```
The correct behavior is to keep the string as-is:
```svelte
<script context="module">
export const metadata = {"price":"$10"};
const { price } = metadata;
</script>
```
=> Frontmatter containing `$1` is correctly substituted

.changeset/ten-trainers-reply.md, .changeset/wild-sloths-drop.md, packages/mdsvex/src/transformers/index.ts, packages/mdsvex/src/types.ts
Today, as of [mdsvex@0.11.0](https://github.com/pngwn/MDsveX/releases/tag/mdsvex%400.11.0), a custom [highlighter function](https://mdsvex.pngwn.io/docs#highlight) is not aware of the filename of the file being processed by MDsveX, and there is no way (that i am aware of) to get around this using the public API.
This issue adds such support by passing additional `filename` positional param for highlighter.
Having `filename` in highlighter will allow more complex customization. Specifically, I'm trying to have the syntax highlighter read the source code from file system provided in a meta line, something like this:
```svelte
/// source=./examples/an-example.svelte
```
This allows keeping certain example source code in a separate file, making better use of editor support, enabling …
=> Pass filename to highlighter

.changeset/dry-houses-pay.md, packages/mdsvex/src/types.ts
This enables TypeScript to autocomplete the types of settings passed to unified plugins like so:
```js
mdsvex({
rehypePlugins: [[rehypeExternalLinks, { target: "_blank" }]]
})
```
=> Infer the settings type when using unified plugins with settings

.github/workflows/mdsvex.yaml, package.json, packages/mdsvex/src/index.ts, pnpm-lock.yaml
CI is currently failing on `master`
=> chore: fix formatting

.changeset/long-comics-march.md, packages/mdsvex/package.json, packages/mdsvex/rollup.config.js
fixes a couple of issues:
- extension for module must be `.mjs` for node compatibility
- removed `browser` field because that file didn't resolve, so no one could have been using it
=> add exports map to package.json

package.json, packages/mdsvex/package.json, packages/svast/package.json
It's nice to be able to run the `mdsvex` tests on a standalone basis. It'd also allow you to incrementally migrate one project at a time to vitest
=> run tests with pnpm -r

packages/mdsvex/package.json
adding `types` fields to `package.json` fixes #648
=> export types

.changeset/nice-pumas-hug.md, packages/mdsvex/src/index.ts, packages/mdsvex/test/it/mdsvex.spec.ts
Upgrading to the latest `mdsvex` made the build of my project fail...while investigating the reason i found the culprit here...basically since the preprocessor is invoked on multiple files it could happen that on some files they enter the `if` that guards the `add_layouts` even after some file already called `parser.process` which means that the `parser` is already frozen.
This also meant that the code to process the layouts were unnecessarily run multiple times.
I've tried to create a reproduction to add a test but i failed to do so...on my pc if i build my project `handle_path` takes up to 30ms to complete (which causes the race condition)...but on a fresh project `handle_path` doesn't take more than 0.2 ms. Which is weird because `handle_path` just imports `path` from node. 🤷🏼 
However …
=> fix: prevent race condition with `add_layouts`

packages/site/src/routes/_docs.svtext
The approach to shiki usage in the current documentation requires explicit listing of all of the needed languages. This makes shiki+mdsvex use challenging.
Given [`highlighter`](https://github.com/pngwn/MDsveX/blob/main/packages/mdsvex/src/types.ts#L173) expects and `shiki.codeToHtml` returns `Promise<string>`, we can avoid having to precompile with an explicit list.
Relates to #636
=> docs: Avoid explicit shiki languages list
