pngwn/MDsveX

- README.md
- package.json
- src/parse.ts
- test/parse.spec.ts
- yarn.lock
Adds support for global and file specific custom layouts.
> Custom layouts

- README.md
- src/md/svelteParse.ts
- test/svelte-block.spec.ts
Added Svelte block syntax support. Should work just fine, all tests passes.
> Svelte block syntax support

- package.json
- src/index.js
- test/it/mdsvex.test.js
- yarn.lock
- Throw an error with a helpful message when `layouts` rather than `layout` is passed.
- Warns in the console when an unknown option is passed, and displays a list of valid options.
I decided against proxying `layouts` to `layout` because I don't want to pollute the options.
> 50 layouts warning

- site/src/routes/_docs.svtext
- site/src/routes/docs.svelte
Documents use with `svelte-loader` (via webpack) and direct use with` svelte.preprocess`.
> 60 docs svelte loader

- site/src/routes/_docs.svtext
> Fix doc typo

- README.md
Rendered https://github.com/benmccann/MDsveX/tree/patch-1
> Remove extraneous backticks

- site/src/routes/_docs.svtext
- src/transformers/index.js
- test/_fixtures/hybrid/output/code-escaping.svelte
- test/_fixtures/hybrid/output/code-highlight-nesting.svelte
- test/it/code_highlighting.test.js
fixes newline https://github.com/pngwn/MDsveX/issues/99#issuecomment-656738572
> fixes newline in highlight

- .eslintrc.js
- src/index.ts
- src/parsers/index.ts
- src/transformers/index.ts
- src/types.ts
Cleans up types and refactors how layouts are worked out a little.
> Refactor layouts

- .changeset/cuddly-crabs-fail.md
- packages/svast/index.d.ts
> feat(svast): fix string literal type in BranchingBlock interface

- .changeset/beige-glasses-check.md
- packages/svast/README.md
- packages/svast/index.d.ts
- packages/svelte-parse/src/main.ts
> 173 comment value

- .changeset/loud-humans-relate.md
- packages/svelte-parse/src/main.ts
- packages/svelte-parse/test/element.test.ts
> 181 modifier no value

- .changeset/short-kids-eat.md
- packages/mdsvex/package.json
- packages/mdsvex/src/transformers/index.ts
- packages/mdsvex/src/types.ts
- packages/mdsvex/test/it/code_highlighting.test.ts
- pnpm-lock.yaml
Adds support for async code highlight functions:
Closes: #205
> 205 async highlighters

- .changeset/twenty-penguins-vanish.md
- packages/mdsvex/package.json
- packages/mdsvex/src/transformers/index.ts
- packages/mdsvex/test/it/code_highlighting.test.ts
- pnpm-lock.yaml
> Svelte syntax

- .changeset/strange-ties-rush.md
- packages/mdsvex/src/transformers/index.ts
- packages/mdsvex/test/it/code_highlighting.test.ts
> feat(mdsvex): make language defs on fenced code blocks case instensitive

- .changeset/few-fireants-vanish.md
- packages/mdsvex/src/main.ts
- packages/mdsvex/src/transformers/index.ts
> 211 escape util

- packages/site/src/routes/_docs.svtext
> Document the ability to import markdown files as components

- .changeset/six-wasps-move.md
- packages/mdsvex/package.json
- packages/mdsvex/src/define-config.ts
- packages/mdsvex/src/main.ts
For some reason stuff is broken, need to revert so we can unpick it.
> Revert 401 feat/defineconfig

- .changeset/strong-news-end.md
- packages/mdsvex/src/transformers/index.ts
- packages/mdsvex/test/_fixtures/hybrid/input/tags-in-frontmatter.svx
- packages/mdsvex/test/_fixtures/hybrid/output/tags-in-frontmatter.svelte
> fix(mdsvex): escape script and style tags in frontmatter

- .changeset/rotten-rabbits-fly.md
- .github/workflows/mdsvex.yaml
- .github/workflows/release.yml
- packages/mdsvex/package.json
- packages/mdsvex/src/index.ts
- packages/mdsvex/src/types.ts
- pnpm-lock.yaml
* updates peer dependencies supported versions
* adds name property to preprocessor
* needs input for proper changeset
Closes #518.
> support svelte@4

- .changeset/ninety-months-film.md
- packages/mdsvex/src/index.ts
- packages/mdsvex/src/main.ts
> 507 export highlight

- .changeset/strong-toes-smile.md
- packages/mdsvex/globals.d.ts
- packages/site/src/routes/_docs.svtext
> Fix typescript module declaration

- .changeset/wicked-owls-fold.md
- packages/mdsvex/package.json
> fix exports

- .changeset/chilly-cycles-listen.md
- packages/mdsvex/src/index.ts
- packages/mdsvex/src/transformers/index.ts
- packages/mdsvex/src/types.ts
- packages/mdsvex/test/it/code_highlighting.spec.ts
- packages/site/src/routes/_docs.svtext
> Optimise code

- .changeset/popular-donuts-think.md
- .changeset/shiny-parrots-fly.md
- package.json
- packages/mdsvex/package.json
- packages/mdsvex/rollup.config.js
- packages/mdsvex/src/index.ts
- packages/mdsvex/src/transformers/index.ts
- packages/mdsvex/src/utils.ts
- packages/test-app/src/Layout.svelte
- packages/test-app/src/lib/Layout.svelte
- packages/test-app/svelte.config.js
- pnpm-lock.yaml
> Replace process polyfill with something that isn't ridiculous
